/* Capital Clash: the three event sets. Each has 100 different events (95 numbered + 5 Skip), so no event repeats on the board.
   Classic = the balanced mix. Wall Street = steady: small moves (max 3). Crypto = volatile: big and small swings (max 9), 12 events with a random sign.
   Format: "Name (+n)" / "Name (-n)" / "Name (Skip)" / "Name (±n)" = the sign is chosen at random when the board is built.
   The numbers are scaled to the game length by buildBalancedTiles(); only the spread between small and big is kept. */
const EVENT_SETS = {
    classic: [
        "Retail Surge (+4)", "Debt Default (-1)", "Currency Gain (+3)", "Pension Crisis (-1)",
        "Patent Granted (+3)", "Hedge Fund Collapse (-3)", "Oil Discovery (+3)", "Bond Maturity (+3)",
        "Bad Headline (-1)", "Interest Earned (+4)", "Speculation Loss (-2)", "Dividend Yield (+3)",
        "Consulting Fee (+2)", "Supply Halt (Skip)", "Savings Bonus (+3)", "Rate Cut (+1)",
        "Interest Spike (-3)", "Rental Income (+3)", "Gold Rush (+2)", "Margin Call (-3)",
        "Brand Deal (+2)", "Stock Split (+3)", "Credit Downgrade (-1)", "Merger Bonus (+1)",
        "Product Launch (+2)", "Cyber Attack (-5)", "Oil Spill (-5)", "VC Investment (+2)",
        "Trade War (-5)", "Overpaid Deal (-3)", "Startup Exit (+1)", "Real Estate Boom (+3)",
        "Supply Halt (Skip)", "Housing Dip (-1)", "Green Energy Grant (+1)", "Foreign Investment (+2)",
        "Bad Loan (-1)", "Bubble Eruption (-4)", "Sponsor Deal (+5)", "Late Penalty (-2)",
        "Dividend Payout (+4)", "Supply Shock (-5)", "Royalty Check (+1)", "Bear Market (-5)",
        "Loan Forgiven (+2)", "Audit Penalty (-2)", "Crypto Rally (+3)", "Angel Bonus (+5)",
        "Supply Halt (Skip)", "Trade Surplus (+1)", "Partnership Signed (+5)", "Lucky Contract (+1)",
        "Tax Refund (+3)", "Bankruptcy Wave (-3)", "Product Recall (-5)", "Data Breach (-2)",
        "Bank Fee (-3)", "Energy Shortage (-1)", "Recession Dip (-4)", "Boycott (-5)",
        "Lawsuit Filed (-2)", "Record Profits (+4)", "Venture Round (+2)", "Inflation Leak (-3)",
        "Fine Imposed (-1)", "Tariff Hike (-1)", "Reserve Vault (+3)", "Storm Damage (-4)",
        "Rent Hike (-4)", "Market Crash (-3)", "Hot Tip (+4)", "Buyback Program (+2)",
        "Liquidity Crunch (-3)", "Inheritance (+2)", "Embargo (-4)", "Supply Halt (Skip)",
        "Export Deal (+5)", "Crowdfunding Hit (+5)", "Housing Rally (+3)", "Currency Slump (-4)",
        "Bull Run (+4)", "Stimulus Package (+5)", "Tax Audit (-2)", "Lottery Win (+2)",
        "Factory Fire (-5)", "Broker Error (-3)", "Panic Selling (-2)", "Pension Boost (+2)",
        "IPO Launch (+1)", "Supply Halt (Skip)", "Contract Lost (-4)", "Shipping Delay (-1)",
        "Failed Merger (-2)", "Commodity Spike (+3)", "Portfolio Shield (+2)", "Tech Boom (+1)",
        "Strike Action (-2)", "Fraud Found (-4)", "Insider Scandal (-2)", "Crop Failure (-2)"
    ],
    wallstreet: [
        "Dividend Cut (-3)", "Municipal Bond Gain (+1)", "Stagflation Fear (-1)", "Safe Haven Inflow (+1)",
        "Yield Pickup (+2)", "Merger Premium (+2)", "Rating Cut (-3)", "Lower Inflation (+2)",
        "Stable Outlook (+3)", "GDP Miss (-3)", "Profit Warning (-2)", "Cash Flow Surge (+2)",
        "Roadshow Success (+3)", "Guidance Raised (+2)", "Share Repurchase (+3)", "Hedged Book (+2)",
        "Liquidity Squeeze (-1)", "Trading Halt (Skip)", "Index Removal (-2)", "Blue Chip Dividend (+1)",
        "Yield Curve Inversion (-2)", "Secondary Offering Hit (+1)", "Value Pick (+2)", "Black Monday (-3)",
        "GDP Beat (+1)", "Coupon Income (+3)", "Share Split (+1)", "Cost Overrun (-3)",
        "Short Report (-3)", "Cash Dividend (+1)", "Deal Collapse (-3)", "Rating Watch (-1)",
        "Capital Gain (+1)", "Class Action (-1)", "Order Book Full (+3)", "Jobs Report Beat (+3)",
        "Index Inclusion (+3)", "Recall Costs (-3)", "Bond Rally (+2)", "Inventory Glut (-1)",
        "Correction (-2)", "ETF Inflow (+3)", "Trading Fee (-2)", "Volatility Spike (-1)",
        "Dividend Reinvested (+2)", "Hedge Misfire (-2)", "Tariff Shock (-2)", "Primary Offering (+2)",
        "Annuity Payout (+2)", "Pension Fund Buy (+3)", "Guidance Lowered (-1)", "Consumer Confidence Down (-2)",
        "Strong Balance Sheet (+2)", "Rate Hike (-3)", "Pension Shortfall (-1)", "Balanced Fund Gain (+3)",
        "Accounting Error (-2)", "Executive Exit (-2)", "Quarterly Loss (-2)", "Bond Selloff (-1)",
        "Debt Ceiling Scare (-2)", "Sector Rotation Out (-2)", "Earnings Miss (-2)", "Capital Reserve (+1)",
        "Overvaluation Warning (-3)", "Fed Pause (+1)", "Treasury Yield (+3)", "Quarterly Earnings Beat (+2)",
        "Bond Coupon (+1)", "Weak Jobs Report (-3)", "Currency Drag (-1)", "Trading Halt (Skip)",
        "Compliance Fine (-3)", "Policy Easing (+1)", "Trading Halt (Skip)", "Steady Growth (+2)",
        "Blue Chip Rally (+2)", "Preferred Dividend (+1)", "Sector Rotation In (+2)", "Retained Earnings (+1)",
        "Trading Halt (Skip)", "Analyst Downgrade (-2)", "SEC Inquiry (-2)", "Price Pressure (-3)",
        "Buyback Announced (+2)", "Trade Deal Signed (+2)", "Shareholder Revolt (-3)", "Collateral Call (-1)",
        "Institutional Buying (+3)", "Trading Halt (Skip)", "Hedge Success (+2)", "Supply Chain Delay (-1)",
        "Tax Review (-2)", "Credit Upgrade (+2)", "Fund Outflow (-1)", "Analyst Upgrade (+2)",
        "Lockup Expiry (-2)", "Consumer Confidence Up (+1)", "IPO Delayed (-3)", "Brokerage Fee (-3)"
    ],
    crypto: [
        "Withdrawal Halt (-9)", "Cross-Chain Win (+1)", "Liquidation Cascade (-1)", "Slippage Loss (-2)",
        "Mining Ban (-1)", "Funding Squeeze (-3)", "Protocol Upgrade (+4)", "51% Attack (-8)",
        "Wallet Drained (-8)", "Token Swap (±4)", "Audit Passed (+1)", "Retail FOMO (+8)",
        "Validator Reward (+7)", "GameFi Surge (+5)", "Gas Fee (-1)", "Fork Failure (-4)",
        "Governance Vote (±8)", "Whale Move (±3)", "Altseason (+6)", "VC Seed (+1)",
        "Hard Fork (±4)", "Validator Slashing (-9)", "Memecoin Frenzy (±5)", "Regulation Ban (-1)",
        "Exploit (-9)", "Chain Reorg (-1)", "Flash Crash (-2)", "Testnet Success (+1)",
        "Sentiment Swing (±7)", "Mining Reward (+3)", "Crypto Winter (-4)", "Ecosystem Fund (+3)",
        "Hash Rate Record (+1)", "DEX Listing (+6)", "Oracle Update (±8)", "Airdrop Lottery (±5)",
        "Leverage Bet (±6)", "Bridge Hack (-1)", "Lost Keys (-2)", "Chain Halt (Skip)",
        "Smart Contract Bug (-2)", "SEC Leak (-5)", "Staking Reward (+4)", "Social Media Hack (-4)",
        "Delisting (-2)", "Tax Crackdown (-7)", "Bridge Opened (+1)", "Governance Win (+2)",
        "Token Unlock Dump (-8)", "Insolvency Rumor (-6)", "Wallet Adoption (+5)", "Oracle Failure (-7)",
        "Memecoin Pump (+5)", "ETF Approved (+4)", "Exchange Hack (-1)", "Scam Token (-3)",
        "Honeypot Trap (-9)", "Whitelist Win (+2)", "Protocol Merge (±3)", "Halving Hype (+5)",
        "Mempool Jam (-9)", "Airdrop (+6)", "Exit Scam (-7)", "Celebrity Tweet (+7)",
        "Whale Accumulation (+4)", "Developer Grant (+7)", "Moon Rally (+3)", "Chain Halt (Skip)",
        "Airdrop Farmers Dump (-6)", "Whale Dump (-8)", "Rug Pull (-5)", "Token Burn (+5)",
        "Phishing Scam (-2)", "Exchange Listing (+2)", "Dev Rug (-7)", "DAO Bonus (+1)",
        "Metaverse Hype (+3)", "Yield Farming (+1)", "Chain Halt (Skip)", "Elon Tweet (±7)",
        "Bull Flag (+2)", "Short Squeeze (+3)", "Liquidity Pool (+6)", "Chain Halt (Skip)",
        "Stablecoin Inflow (+3)", "NFT Boom (+4)", "Golden Cross (+1)", "Mainnet Launch (+2)",
        "Cold Vault (+9)", "Network Outage (-2)", "Leverage Wipeout (-6)", "Death Cross (-8)",
        "KYC Freeze (-3)", "Partnership Announced (+3)", "De-Peg (-9)", "Merchant Adoption (+8)",
        "Exchange Rumor (±6)", "FUD Wave (-2)", "Layer-2 Boom (+1)", "Chain Halt (Skip)"
    ],
};
